### ISSUE TITLE
Private vs Public

### ISSUE THREAD

**Issue by rasagy** [mapbox/osm-analysis-dashboard#13]
Forking the conversation around documenting the project/opening the repo from [here](https://github.com/mapbox/osm-analysis-dashboard/issues/9#issuecomment-330739661).

From what I’m seeing, this code is only front-end code (tilesets are read-only). I see no harm in making this public so others can understand how to build a project like this. It would also enable us to document the project in the Readme/wiki here.

@batpad Based on the https://github.com/mapbox/osm-analysis-dashboard/issues/9#issuecomment-330739661 I think both Jennings & Ramya would prefer to make this repo open and document the project using wiki/Readme. Want to go ahead and make it open?

cc @jenningsanderson @ramyaragupathy

**Comment by jenningsanderson** [comment]
👍
