### ISSUE TITLE
Things to ship for SOTM Asia

### ISSUE THREAD

**Issue by ramyaragupathy** [mapbox/osm-analysis-dashboard#9]
Per discussion today listing down items, in order of importance, that needs to be shipped for the SOTM Asia presentation:

- [x] Move the legend/Color ramp from the map div to the sidebar
- [x] Specify min & max property values for legends. This can give a good overview on the range distribution for a particular property
- [x] Geocoder to switch between cities
- [x] Help text for each property in the sidebar
- [x] A link to resources (methodology, github repo) in the sidebar
- [x] Pop up on hover with just selected property
- [x] Year & Quarter information on each side of the map compare
- [x] Change the text from `filter` to `Compare Quarters` 
- [x] Move city/place labels one layer above the tile view
- [x] Open in OSM link for a particular viewport

cc @planemad @rasagy @batpad @jenningsanderson @tridip1931

**Comment by jenningsanderson** [comment]
### Update with (https://github.com/mapbox/osm-analysis-dashboard/pull/23)
- Filter Button now changes color for year property too
- Filter property persists through the reload (with description)
- Zoom Scalars work now with the legend as well; color scale changes with zoom on per-property basis 🤓 
- Units in the legend

**Comment by ramyaragupathy** [comment]
Thanks for the support team, I was able to showcase the frontend in the talk.
